### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaPackaging/WinRPM.jl#145] opened 2018-03-09 10:21 UTC
I realize this is a recurring kind of problem but after reading previous issues I'm still unclear on how to debug this or how I can work around it. Both failing URLs can be opened successfully in a browser.
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> ENV["JULIA_PKGDIR"]=mktempdir()
"C:\\Users\\gunnarf\\AppData\\Local\\Temp\\jl_C3C0.tmp"

julia> Pkg.init()
INFO: Initializing package repository C:\Users\gunnarf\AppData\Local\Temp\jl_C3C0.tmp\v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl

julia> Pkg.add("WinRPM")
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of BufferedStreams from https://github.com/BioJulia/BufferedStreams.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of LibExpat from https://github.com/JuliaIO/LibExpat.jl.git
INFO: Cloning cache of Libz from https://github.com/BioJulia/Libz.jl.git
INFO: Cloning cache of SHA from https://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from https://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of WinRPM from https://github.com/JuliaPackaging/WinRPM.jl.git
INFO: Installing BinDeps v0.8.7
INFO: Installing BufferedStreams v0.4.0
INFO: Installing Compat v0.57.0
INFO: Installing LibExpat v0.4.1
INFO: Installing Libz v0.2.4
INFO: Installing SHA v0.5.6
INFO: Installing URIParser v0.3.1
INFO: Installing WinRPM v0.3.1
INFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/b367d143ef9d96524f0259e537f6f2e079b7d28cffe124fc43b1d5a4fbdcb5db-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/b367d143ef9d96524f0259e537f6f2e079b7d28cffe124fc43b1d5a4fbdcb5db-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/b367d143ef9d96524f0259e537f6f2e079b7d28cffe124fc43b1d5a4fbdcb5db-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/b367d143ef9d96524f0259e537f6f2e079b7d28cffe124fc43b1d5a4fbdcb5db-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/b367d143ef9d96524f0259e537f6f2e079b7d28cffe124fc43b1d5a4fbdcb5db-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/b367d143ef9d96524f0259e537f6f2e079b7d28cffe124fc43b1d5a4fbdcb5db-primary.xml.gz
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/b367d143ef9d96524f0259e537f6f2e079b7d28cffe124fc43b1d5a4fbdcb5db-primary.xml.gz
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/8238de51655a6fddfa8a464e3b682525e03f5455ea7976dc53fbf6ef15c6887a-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/8238de51655a6fddfa8a464e3b682525e03f5455ea7976dc53fbf6ef15c6887a-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/8238de51655a6fddfa8a464e3b682525e03f5455ea7976dc53fbf6ef15c6887a-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/8238de51655a6fddfa8a464e3b682525e03f5455ea7976dc53fbf6ef15c6887a-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/8238de51655a6fddfa8a464e3b682525e03f5455ea7976dc53fbf6ef15c6887a-primary.xml.gz
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/8238de51655a6fddfa8a464e3b682525e03f5455ea7976dc53fbf6ef15c6887a-primary.xml.gz
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/8238de51655a6fddfa8a464e3b682525e03f5455ea7976dc53fbf6ef15c6887a-primary.xml.gz
INFO: Package database updated
```

**Comment by nalimilan** [comment] 2018-03-09 12:57
Duplicate of https://github.com/JuliaPackaging/WinRPM.jl/issues/47. The PowerShell method appears to work it, so https://github.com/JuliaPackaging/WinRPM.jl/pull/144/ should fix it.

**Closed** 2018-03-09 12:57 UTC
