### ISSUE TITLE
Unknown download failure, error code: 2148270085

### ISSUE THREAD

**Issue by lucaro** [JuliaPackaging/WinRPM.jl#99] opened 2017-02-10 09:30 UTC
On julia 0.5.0, when trying to build the current version of WinRPM I get the following output:

```
julia> Pkg.build("WinRPM")
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml

```

Is there a way around this?

**Comment by nalimilan** [comment] 2017-02-10 09:35
Duplicate of https://github.com/JuliaPackaging/WinRPM.jl/issues/57. You can try the solution here, but it doesn't always work IIRC: https://github.com/JuliaPackaging/WinRPM.jl/issues/57#issuecomment-150828177

**Closed by nalimilan** 2017-02-10 09:35 UTC
